version: '3'
services:
  kitsune-back:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development

  kitsune-front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development